"""Added blocklist token table

Revision ID: 260ee7e823df
Revises: 96a6bf80cff5
Create Date: 2023-07-28 07:56:39.613306

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "260ee7e823df"
down_revision = "96a6bf80cff5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocklist_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blocklist_token", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blocklist_token_jti"), ["jti"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blocklist_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blocklist_token_jti"))

    op.drop_table("blocklist_token")
    # ### end Alembic commands ###
