"""Add user public id and backref for role

Revision ID: 4b3db6d89273
Revises: 427e3cf281ac
Create Date: 2023-06-23 11:15:17.933763

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b3db6d89273"
down_revision = "427e3cf281ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###fd
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("public_id", sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ["public_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("public_id")

    # ### end Alembic commands ###
