"""remove user public id

Revision ID: 96a6bf80cff5
Revises: f09861c6a1a2
Create Date: 2023-07-26 04:29:22.686943

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "96a6bf80cff5"
down_revision = "f09861c6a1a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("public_id")
        batch_op.drop_column("public_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("public_id", mysql.VARCHAR(length=36), nullable=False))
        batch_op.create_index("public_id", ["public_id"], unique=False)

    # ### end Alembic commands ###
